---
-
  hosts: all
  gather_facts: true 

  tasks: 
    - name: Display all Running Service
      win_shell: get-service
      register: servicevar
       
    - name: Show output
      debug:
        var: servicevar
        when: "{{servicevar.Status == 'Running'}}"

# You can use below way as well
#when: 
 #       - ansible_distribution == "CentOS" 
  #      - ansible_distribution_major_version | int >= 7

...
