---
wingrp:
 hosts:
  Vikram:
   ansible_user: Administrator
   ansible_password: Vikram@123
   ansible_winrm_transport: ntlm
   ansible_connection: winrm
   ansible_port: 5986
   ansible_winrm_server_cert_validation: ignore
...
