---
-

  hosts: all
  
  vars_files:
   - ext_variable.yml
   

  tasks:
    - name: stop a bits service 
      win_service: 
        name: "{{item}}"
        state: stopped
      loop:
         "{{servicesneedstodisable}}"
         
...
